In [1]:
import torch

In [2]:
# 一维标量的例子

In [3]:
a = torch.tensor(2., requires_grad=True)
b = torch.tensor(4., requires_grad=True)

In [4]:
f1 = 2 * a
f2 = a * b

In [5]:
y = f1 + f2

In [6]:
y.backward()

In [7]:
a.grad, b.grad

(tensor(6.), tensor(2.))

In [8]:
# 多维矩阵的例子

In [9]:
c = torch.arange(1.0, 9.0).reshape(2,4)
c

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])

In [10]:
c.requires_grad_(True)
c

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]], requires_grad=True)

In [11]:
d = 4 * c

In [12]:
# e = torch.mul(d, d)
e = d * d

In [13]:
f = e.mean()

In [14]:
f.backward()

In [15]:
c.grad

tensor([[ 4.,  8., 12., 16.],
        [20., 24., 28., 32.]])

In [16]:
# 所求的某变量不需要求导：

(tensor(408., grad_fn=<MeanBackward0>), tensor(408.))

In [17]:
# 1
with torch.no_grad():
    g = e.mean()
f, g

(tensor(408., grad_fn=<MeanBackward0>), tensor(408.))

In [18]:
# 2
h = f.detach()
f, h

(tensor(408., grad_fn=<MeanBackward0>), tensor(408.))